### ISSUE TITLE
Elanor not available

### ISSUE THREAD

**Issue by checksummaster** [cvanelteren/splitboard#1]
Elanor sub project seem not available (it private?)
Anyway, thanks for the code, it exactly what I wanted to do.
(Maybe add a micro trackball near the pinky to keep him actif)

**Comment by cvanelteren** [comment]
Hey @checksummaster, the repo is still private. It has been on my backlog for a file to clean it up and release it. I designed it using Kicad. If you  want, I can upload the Gerbers / Kicad files for now. Would this work for you?

**Comment by checksummaster** [comment]
Hi, yes it can help. By the way, great job with the esp32.

**Comment by cvanelteren** [comment]
The repo is now live on https://github.com/cvanelteren/Elanor. Happy hacking!
